name: manganese_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_map:
  flutter_bloc:
  bloc:
  shared_preferences:
  equatable:
  photo_view:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/alloy/almn.png
    - assets/alloy/femn.png
    - assets/alloy/mn.jpg
    - assets/alloy/simn.jpg
    - assets/alloy/stmn.png
    - assets/molecules/0.png
    - assets/molecules/1.png
    - assets/molecules/3.png
    - assets/molecules/4.jpg
    - assets/molecules/5.jpg
    - assets/periodic_table.png
    - assets/periodic_table_dark.png
    - assets/country_flags/za.png
    - assets/country_flags/cn.png
    - assets/country_flags/au.png
    - assets/country_flags/ga.png
    - assets/country_flags/br.png
    - assets/country_flags/in.png
    - assets/country_flags/my.png
    - assets/country_flags/ua.png
    - assets/country_flags/kz.png
    - assets/country_flags/gh.png
    - assets/map/dark/3/0/0.png
    - assets/map/dark/3/0/1.png
    - assets/map/dark/3/0/2.png
    - assets/map/dark/3/0/3.png
    - assets/map/dark/3/0/4.png
    - assets/map/dark/3/0/5.png
    - assets/map/dark/3/0/6.png
    - assets/map/dark/3/0/7.png
    - assets/map/dark/3/1/0.png
    - assets/map/dark/3/1/1.png
    - assets/map/dark/3/1/2.png
    - assets/map/dark/3/1/3.png
    - assets/map/dark/3/1/4.png
    - assets/map/dark/3/1/5.png
    - assets/map/dark/3/1/6.png
    - assets/map/dark/3/1/7.png
    - assets/map/dark/3/2/0.png
    - assets/map/dark/3/2/1.png
    - assets/map/dark/3/2/2.png
    - assets/map/dark/3/2/3.png
    - assets/map/dark/3/2/4.png
    - assets/map/dark/3/2/5.png
    - assets/map/dark/3/2/6.png
    - assets/map/dark/3/2/7.png
    - assets/map/dark/3/3/0.png
    - assets/map/dark/3/3/1.png
    - assets/map/dark/3/3/2.png
    - assets/map/dark/3/3/3.png
    - assets/map/dark/3/3/4.png
    - assets/map/dark/3/3/5.png
    - assets/map/dark/3/3/6.png
    - assets/map/dark/3/3/7.png
    - assets/map/dark/3/4/0.png
    - assets/map/dark/3/4/1.png
    - assets/map/dark/3/4/2.png
    - assets/map/dark/3/4/3.png
    - assets/map/dark/3/4/4.png
    - assets/map/dark/3/4/5.png
    - assets/map/dark/3/4/6.png
    - assets/map/dark/3/4/7.png
    - assets/map/dark/3/5/0.png
    - assets/map/dark/3/5/1.png
    - assets/map/dark/3/5/2.png
    - assets/map/dark/3/5/3.png
    - assets/map/dark/3/5/4.png
    - assets/map/dark/3/5/5.png
    - assets/map/dark/3/5/6.png
    - assets/map/dark/3/5/7.png
    - assets/map/dark/3/6/0.png
    - assets/map/dark/3/6/1.png
    - assets/map/dark/3/6/2.png
    - assets/map/dark/3/6/3.png
    - assets/map/dark/3/6/4.png
    - assets/map/dark/3/6/5.png
    - assets/map/dark/3/6/6.png
    - assets/map/dark/3/6/7.png
    - assets/map/dark/3/7/0.png
    - assets/map/dark/3/7/1.png
    - assets/map/dark/3/7/2.png
    - assets/map/dark/3/7/3.png
    - assets/map/dark/3/7/4.png
    - assets/map/dark/3/7/5.png
    - assets/map/dark/3/7/6.png
    - assets/map/dark/3/7/7.png
    - assets/map/dark/4/3/10.png
    - assets/map/dark/4/3/11.png
    - assets/map/dark/4/3/6.png
    - assets/map/dark/4/3/7.png
    - assets/map/dark/4/3/8.png
    - assets/map/dark/4/3/9.png
    - assets/map/dark/4/4/10.png
    - assets/map/dark/4/4/11.png
    - assets/map/dark/4/4/6.png
    - assets/map/dark/4/4/7.png
    - assets/map/dark/4/4/8.png
    - assets/map/dark/4/4/9.png
    - assets/map/dark/4/5/10.png
    - assets/map/dark/4/5/11.png
    - assets/map/dark/4/5/6.png
    - assets/map/dark/4/5/7.png
    - assets/map/dark/4/5/8.png
    - assets/map/dark/4/5/9.png
    - assets/map/dark/4/6/10.png
    - assets/map/dark/4/6/11.png
    - assets/map/dark/4/6/6.png
    - assets/map/dark/4/6/7.png
    - assets/map/dark/4/6/8.png
    - assets/map/dark/4/6/9.png
    - assets/map/dark/4/7/10.png
    - assets/map/dark/4/7/11.png
    - assets/map/dark/4/7/6.png
    - assets/map/dark/4/7/7.png
    - assets/map/dark/4/7/8.png
    - assets/map/dark/4/7/9.png
    - assets/map/dark/5/10/14.png
    - assets/map/dark/5/10/15.png
    - assets/map/dark/5/10/16.png
    - assets/map/dark/5/10/17.png
    - assets/map/dark/5/10/18.png
    - assets/map/dark/5/10/19.png
    - assets/map/dark/5/10/20.png
    - assets/map/dark/5/11/14.png
    - assets/map/dark/5/11/15.png
    - assets/map/dark/5/11/16.png
    - assets/map/dark/5/11/17.png
    - assets/map/dark/5/11/18.png
    - assets/map/dark/5/11/19.png
    - assets/map/dark/5/11/20.png
    - assets/map/dark/5/12/14.png
    - assets/map/dark/5/12/15.png
    - assets/map/dark/5/12/16.png
    - assets/map/dark/5/12/17.png
    - assets/map/dark/5/12/18.png
    - assets/map/dark/5/12/19.png
    - assets/map/dark/5/12/20.png
    - assets/map/dark/5/13/14.png
    - assets/map/dark/5/13/15.png
    - assets/map/dark/5/13/16.png
    - assets/map/dark/5/13/17.png
    - assets/map/dark/5/13/18.png
    - assets/map/dark/5/13/19.png
    - assets/map/dark/5/13/20.png
    - assets/map/dark/5/8/14.png
    - assets/map/dark/5/8/15.png
    - assets/map/dark/5/8/16.png
    - assets/map/dark/5/8/17.png
    - assets/map/dark/5/8/18.png
    - assets/map/dark/5/8/19.png
    - assets/map/dark/5/8/20.png
    - assets/map/dark/5/9/14.png
    - assets/map/dark/5/9/15.png
    - assets/map/dark/5/9/16.png
    - assets/map/dark/5/9/17.png
    - assets/map/dark/5/9/18.png
    - assets/map/dark/5/9/19.png
    - assets/map/dark/5/9/20.png
    - assets/map/dark/6/18/29.png
    - assets/map/dark/6/18/30.png
    - assets/map/dark/6/18/31.png
    - assets/map/dark/6/18/32.png
    - assets/map/dark/6/18/33.png
    - assets/map/dark/6/18/34.png
    - assets/map/dark/6/18/35.png
    - assets/map/dark/6/18/36.png
    - assets/map/dark/6/18/37.png
    - assets/map/dark/6/18/38.png
    - assets/map/dark/6/18/39.png
    - assets/map/dark/6/19/29.png
    - assets/map/dark/6/19/30.png
    - assets/map/dark/6/19/31.png
    - assets/map/dark/6/19/32.png
    - assets/map/dark/6/19/33.png
    - assets/map/dark/6/19/34.png
    - assets/map/dark/6/19/35.png
    - assets/map/dark/6/19/36.png
    - assets/map/dark/6/19/37.png
    - assets/map/dark/6/19/38.png
    - assets/map/dark/6/19/39.png
    - assets/map/dark/6/20/29.png
    - assets/map/dark/6/20/30.png
    - assets/map/dark/6/20/31.png
    - assets/map/dark/6/20/32.png
    - assets/map/dark/6/20/33.png
    - assets/map/dark/6/20/34.png
    - assets/map/dark/6/20/35.png
    - assets/map/dark/6/20/36.png
    - assets/map/dark/6/20/37.png
    - assets/map/dark/6/20/38.png
    - assets/map/dark/6/20/39.png
    - assets/map/dark/6/21/29.png
    - assets/map/dark/6/21/30.png
    - assets/map/dark/6/21/31.png
    - assets/map/dark/6/21/32.png
    - assets/map/dark/6/21/33.png
    - assets/map/dark/6/21/34.png
    - assets/map/dark/6/21/35.png
    - assets/map/dark/6/21/36.png
    - assets/map/dark/6/21/37.png
    - assets/map/dark/6/21/38.png
    - assets/map/dark/6/21/39.png
    - assets/map/dark/6/22/29.png
    - assets/map/dark/6/22/30.png
    - assets/map/dark/6/22/31.png
    - assets/map/dark/6/22/32.png
    - assets/map/dark/6/22/33.png
    - assets/map/dark/6/22/34.png
    - assets/map/dark/6/22/35.png
    - assets/map/dark/6/22/36.png
    - assets/map/dark/6/22/37.png
    - assets/map/dark/6/22/38.png
    - assets/map/dark/6/22/39.png
    - assets/map/dark/6/23/29.png
    - assets/map/dark/6/23/30.png
    - assets/map/dark/6/23/31.png
    - assets/map/dark/6/23/32.png
    - assets/map/dark/6/23/33.png
    - assets/map/dark/6/23/34.png
    - assets/map/dark/6/23/35.png
    - assets/map/dark/6/23/36.png
    - assets/map/dark/6/23/37.png
    - assets/map/dark/6/23/38.png
    - assets/map/dark/6/23/39.png
    - assets/map/dark/6/24/29.png
    - assets/map/dark/6/24/30.png
    - assets/map/dark/6/24/31.png
    - assets/map/dark/6/24/32.png
    - assets/map/dark/6/24/33.png
    - assets/map/dark/6/24/34.png
    - assets/map/dark/6/24/35.png
    - assets/map/dark/6/24/36.png
    - assets/map/dark/6/24/37.png
    - assets/map/dark/6/24/38.png
    - assets/map/dark/6/24/39.png
    - assets/map/dark/6/25/29.png
    - assets/map/dark/6/25/30.png
    - assets/map/dark/6/25/31.png
    - assets/map/dark/6/25/32.png
    - assets/map/dark/6/25/33.png
    - assets/map/dark/6/25/34.png
    - assets/map/dark/6/25/35.png
    - assets/map/dark/6/25/36.png
    - assets/map/dark/6/25/37.png
    - assets/map/dark/6/25/38.png
    - assets/map/dark/6/25/39.png
    - assets/map/dark/6/26/29.png
    - assets/map/dark/6/26/30.png
    - assets/map/dark/6/26/31.png
    - assets/map/dark/6/26/32.png
    - assets/map/dark/6/26/33.png
    - assets/map/dark/6/26/34.png
    - assets/map/dark/6/26/35.png
    - assets/map/dark/6/26/36.png
    - assets/map/dark/6/26/37.png
    - assets/map/dark/6/26/38.png
    - assets/map/dark/6/26/39.png
    - assets/map/light/3/0/0.png
    - assets/map/light/3/0/1.png
    - assets/map/light/3/0/2.png
    - assets/map/light/3/0/3.png
    - assets/map/light/3/0/4.png
    - assets/map/light/3/0/5.png
    - assets/map/light/3/0/6.png
    - assets/map/light/3/0/7.png
    - assets/map/light/3/1/0.png
    - assets/map/light/3/1/1.png
    - assets/map/light/3/1/2.png
    - assets/map/light/3/1/3.png
    - assets/map/light/3/1/4.png
    - assets/map/light/3/1/5.png
    - assets/map/light/3/1/6.png
    - assets/map/light/3/1/7.png
    - assets/map/light/3/2/0.png
    - assets/map/light/3/2/1.png
    - assets/map/light/3/2/2.png
    - assets/map/light/3/2/3.png
    - assets/map/light/3/2/4.png
    - assets/map/light/3/2/5.png
    - assets/map/light/3/2/6.png
    - assets/map/light/3/2/7.png
    - assets/map/light/3/3/0.png
    - assets/map/light/3/3/1.png
    - assets/map/light/3/3/2.png
    - assets/map/light/3/3/3.png
    - assets/map/light/3/3/4.png
    - assets/map/light/3/3/5.png
    - assets/map/light/3/3/6.png
    - assets/map/light/3/3/7.png
    - assets/map/light/3/4/0.png
    - assets/map/light/3/4/1.png
    - assets/map/light/3/4/2.png
    - assets/map/light/3/4/3.png
    - assets/map/light/3/4/4.png
    - assets/map/light/3/4/5.png
    - assets/map/light/3/4/6.png
    - assets/map/light/3/4/7.png
    - assets/map/light/3/5/0.png
    - assets/map/light/3/5/1.png
    - assets/map/light/3/5/2.png
    - assets/map/light/3/5/3.png
    - assets/map/light/3/5/4.png
    - assets/map/light/3/5/5.png
    - assets/map/light/3/5/6.png
    - assets/map/light/3/5/7.png
    - assets/map/light/3/6/0.png
    - assets/map/light/3/6/1.png
    - assets/map/light/3/6/2.png
    - assets/map/light/3/6/3.png
    - assets/map/light/3/6/4.png
    - assets/map/light/3/6/5.png
    - assets/map/light/3/6/6.png
    - assets/map/light/3/6/7.png
    - assets/map/light/3/7/0.png
    - assets/map/light/3/7/1.png
    - assets/map/light/3/7/2.png
    - assets/map/light/3/7/3.png
    - assets/map/light/3/7/4.png
    - assets/map/light/3/7/5.png
    - assets/map/light/3/7/6.png
    - assets/map/light/3/7/7.png
    - assets/map/light/4/3/10.png
    - assets/map/light/4/3/11.png
    - assets/map/light/4/3/6.png
    - assets/map/light/4/3/7.png
    - assets/map/light/4/3/8.png
    - assets/map/light/4/3/9.png
    - assets/map/light/4/4/10.png
    - assets/map/light/4/4/11.png
    - assets/map/light/4/4/6.png
    - assets/map/light/4/4/7.png
    - assets/map/light/4/4/8.png
    - assets/map/light/4/4/9.png
    - assets/map/light/4/5/10.png
    - assets/map/light/4/5/11.png
    - assets/map/light/4/5/6.png
    - assets/map/light/4/5/7.png
    - assets/map/light/4/5/8.png
    - assets/map/light/4/5/9.png
    - assets/map/light/4/6/10.png
    - assets/map/light/4/6/11.png
    - assets/map/light/4/6/6.png
    - assets/map/light/4/6/7.png
    - assets/map/light/4/6/8.png
    - assets/map/light/4/6/9.png
    - assets/map/light/4/7/10.png
    - assets/map/light/4/7/11.png
    - assets/map/light/4/7/6.png
    - assets/map/light/4/7/7.png
    - assets/map/light/4/7/8.png
    - assets/map/light/4/7/9.png
    - assets/map/light/5/10/14.png
    - assets/map/light/5/10/15.png
    - assets/map/light/5/10/16.png
    - assets/map/light/5/10/17.png
    - assets/map/light/5/10/18.png
    - assets/map/light/5/10/19.png
    - assets/map/light/5/10/20.png
    - assets/map/light/5/11/14.png
    - assets/map/light/5/11/15.png
    - assets/map/light/5/11/16.png
    - assets/map/light/5/11/17.png
    - assets/map/light/5/11/18.png
    - assets/map/light/5/11/19.png
    - assets/map/light/5/11/20.png
    - assets/map/light/5/12/14.png
    - assets/map/light/5/12/15.png
    - assets/map/light/5/12/16.png
    - assets/map/light/5/12/17.png
    - assets/map/light/5/12/18.png
    - assets/map/light/5/12/19.png
    - assets/map/light/5/12/20.png
    - assets/map/light/5/13/14.png
    - assets/map/light/5/13/15.png
    - assets/map/light/5/13/16.png
    - assets/map/light/5/13/17.png
    - assets/map/light/5/13/18.png
    - assets/map/light/5/13/19.png
    - assets/map/light/5/13/20.png
    - assets/map/light/5/8/14.png
    - assets/map/light/5/8/15.png
    - assets/map/light/5/8/16.png
    - assets/map/light/5/8/17.png
    - assets/map/light/5/8/18.png
    - assets/map/light/5/8/19.png
    - assets/map/light/5/8/20.png
    - assets/map/light/5/9/14.png
    - assets/map/light/5/9/15.png
    - assets/map/light/5/9/16.png
    - assets/map/light/5/9/17.png
    - assets/map/light/5/9/18.png
    - assets/map/light/5/9/19.png
    - assets/map/light/5/9/20.png
    - assets/map/light/6/18/29.png
    - assets/map/light/6/18/30.png
    - assets/map/light/6/18/31.png
    - assets/map/light/6/18/32.png
    - assets/map/light/6/18/33.png
    - assets/map/light/6/18/34.png
    - assets/map/light/6/18/35.png
    - assets/map/light/6/18/36.png
    - assets/map/light/6/18/37.png
    - assets/map/light/6/18/38.png
    - assets/map/light/6/18/39.png
    - assets/map/light/6/19/29.png
    - assets/map/light/6/19/30.png
    - assets/map/light/6/19/31.png
    - assets/map/light/6/19/32.png
    - assets/map/light/6/19/33.png
    - assets/map/light/6/19/34.png
    - assets/map/light/6/19/35.png
    - assets/map/light/6/19/36.png
    - assets/map/light/6/19/37.png
    - assets/map/light/6/19/38.png
    - assets/map/light/6/19/39.png
    - assets/map/light/6/20/29.png
    - assets/map/light/6/20/30.png
    - assets/map/light/6/20/31.png
    - assets/map/light/6/20/32.png
    - assets/map/light/6/20/33.png
    - assets/map/light/6/20/34.png
    - assets/map/light/6/20/35.png
    - assets/map/light/6/20/36.png
    - assets/map/light/6/20/37.png
    - assets/map/light/6/20/38.png
    - assets/map/light/6/20/39.png
    - assets/map/light/6/21/29.png
    - assets/map/light/6/21/30.png
    - assets/map/light/6/21/31.png
    - assets/map/light/6/21/32.png
    - assets/map/light/6/21/33.png
    - assets/map/light/6/21/34.png
    - assets/map/light/6/21/35.png
    - assets/map/light/6/21/36.png
    - assets/map/light/6/21/37.png
    - assets/map/light/6/21/38.png
    - assets/map/light/6/21/39.png
    - assets/map/light/6/22/29.png
    - assets/map/light/6/22/30.png
    - assets/map/light/6/22/31.png
    - assets/map/light/6/22/32.png
    - assets/map/light/6/22/33.png
    - assets/map/light/6/22/34.png
    - assets/map/light/6/22/35.png
    - assets/map/light/6/22/36.png
    - assets/map/light/6/22/37.png
    - assets/map/light/6/22/38.png
    - assets/map/light/6/22/39.png
    - assets/map/light/6/23/29.png
    - assets/map/light/6/23/30.png
    - assets/map/light/6/23/31.png
    - assets/map/light/6/23/32.png
    - assets/map/light/6/23/33.png
    - assets/map/light/6/23/34.png
    - assets/map/light/6/23/35.png
    - assets/map/light/6/23/36.png
    - assets/map/light/6/23/37.png
    - assets/map/light/6/23/38.png
    - assets/map/light/6/23/39.png
    - assets/map/light/6/24/29.png
    - assets/map/light/6/24/30.png
    - assets/map/light/6/24/31.png
    - assets/map/light/6/24/32.png
    - assets/map/light/6/24/33.png
    - assets/map/light/6/24/34.png
    - assets/map/light/6/24/35.png
    - assets/map/light/6/24/36.png
    - assets/map/light/6/24/37.png
    - assets/map/light/6/24/38.png
    - assets/map/light/6/24/39.png
    - assets/map/light/6/25/29.png
    - assets/map/light/6/25/30.png
    - assets/map/light/6/25/31.png
    - assets/map/light/6/25/32.png
    - assets/map/light/6/25/33.png
    - assets/map/light/6/25/34.png
    - assets/map/light/6/25/35.png
    - assets/map/light/6/25/36.png
    - assets/map/light/6/25/37.png
    - assets/map/light/6/25/38.png
    - assets/map/light/6/25/39.png
    - assets/map/light/6/26/29.png
    - assets/map/light/6/26/30.png
    - assets/map/light/6/26/31.png
    - assets/map/light/6/26/32.png
    - assets/map/light/6/26/33.png
    - assets/map/light/6/26/34.png
    - assets/map/light/6/26/35.png
    - assets/map/light/6/26/36.png
    - assets/map/light/6/26/37.png
    - assets/map/light/6/26/38.png
    - assets/map/light/6/26/39.png

  fonts:
      - family: Roboto
        fonts:
          - asset: fonts/Roboto/Roboto-Thin.ttf
            weight: 100
          - asset: fonts/Roboto/Roboto-Light.ttf
            weight: 300
          - asset: fonts/Roboto/Roboto-Regular.ttf
            weight: 400
          - asset: fonts/Roboto/Roboto-Medium.ttf
            weight: 500
          - asset: fonts/Roboto/Roboto-Bold.ttf
            weight: 700
          - asset: fonts/Roboto/Roboto-Black.ttf
            weight: 900


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
